DROP TABLE IF EXISTS Fornecedor;

CREATE TABLE Fornecedor (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    RAZAO VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    ENDERECO VARCHAR(255),
    TELEFONE VARCHAR(50)
);

DROP TABLE IF EXISTS Usuario;

CREATE TABLE Usuario (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(50),
    CARGO VARCHAR(100),
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    ATIVO BOOLEAN DEFAULT TRUE,
    NIVEL INT
);

DROP TABLE IF EXISTS Produto;

CREATE TABLE Produto (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    CATEGORIA VARCHAR(100),
    ATIVO BOOLEAN DEFAULT TRUE,
    FORNECEDOR_ID INT,
    FOREIGN KEY (FORNECEDOR_ID) REFERENCES Fornecedor(ID)
);

DROP TABLE IF EXISTS FichaReabastecimentoEstoque;

CREATE TABLE FichaReabastecimentoEstoque (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DATA_CRIACAO DATE NOT NULL,
    STATUS VARCHAR(50)
);

DROP TABLE IF EXISTS Secao;

CREATE TABLE Secao (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(255),
    USUARIO_ID INT,
    FOREIGN KEY (USUARIO_ID) REFERENCES Usuario(ID)
);

DROP TABLE IF EXISTS Estoque;

CREATE TABLE Estoque (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    LOTE VARCHAR(50),
    QUANTIDADE INT NOT NULL,
    QUANTIDADE_CRITICA INT NOT NULL,
    VALIDADE VARCHAR(50),
    DEPARTAMENTO_ID INT,
    PRECO FLOAT,
    PRODUTO_ID INT,
    USUARIO_ID INT,
    SECAO_ID INT,
    FOREIGN KEY (PRODUTO_ID) REFERENCES Produto(ID),
    FOREIGN KEY (USUARIO_ID) REFERENCES Usuario(ID),
    FOREIGN KEY (SECAO_ID) REFERENCES Secao(ID)
);

DROP TABLE IF EXISTS OrdemCompra;

CREATE TABLE OrdemCompra (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    PRODUTO_ID INT,
    QUANTIDADE INT NOT NULL,
    DATA_CRIACAO DATE NOT NULL,
    PRECO_CUSTO DOUBLE,
    STATUS VARCHAR(50),
    USUARIO_ID INT,
    FICHA_ID INT,
    FORNECEDOR_ID INT,
    FOREIGN KEY (PRODUTO_ID) REFERENCES Produto(ID),
    FOREIGN KEY (USUARIO_ID) REFERENCES Usuario(ID),
    FOREIGN KEY (FICHA_ID) REFERENCES FichaReabastecimentoEstoque(ID),
    FOREIGN KEY (FORNECEDOR_ID) REFERENCES Fornecedor(ID)
);

DROP TABLE IF EXISTS DetalheFicha;

CREATE TABLE DetalheFicha (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    PRODUTO_ID INT,
    QUANTIDADE INT NOT NULL,
    FICHA_ID INT,
    FOREIGN KEY (PRODUTO_ID) REFERENCES Produto(ID),
    FOREIGN KEY (FICHA_ID) REFERENCES FichaReabastecimentoEstoque(ID)
);
